from django.urls import path

from .views import (
    TemplateReportCusOrderView,
    TemplateReportOrderSupView,
    TemplateInvoice,
    TemplateBalance,
    TemplatePayment,
    PDFReportCusOrder,
    PDFReportSupOrder,
    PDFInvoice,
    PDFPayment,
    PurchaseReportView,
    SalesReportView,
    PymentReportView,
    CollectionsReportsView,
    BalanceReportView,
    SalesByProductReportView,
    PartnerAccountStatmentView,
    PartnerSearchView,
    PDFCollection,
    TemplateCollection,
)

urlpatterns = [
    path('reports/order-supplier-template/<int:id_order>/',  TemplateReportOrderSupView.as_view(), name='order_supplier_template'),
    path('reports/order-supplier/<int:id_order>/',  PDFReportSupOrder.as_view(), name='report_supplier_order'),
    path('reports/order-customer-template/<int:id_order>/', TemplateReportCusOrderView.as_view(), name='order_customer_template'),
    path('reports/order-customer/<int:id_order>/', PDFReportCusOrder.as_view(), name='report_customer_order'),
    path('reports/invoice-template/<int:id_invoice>/', TemplateInvoice.as_view(), name='invoice_template'),
    path('reports/invoice/<int:id_invoice>/', PDFInvoice.as_view(), name='report_invoice'),
    path('reports/balance-template/<int:partner_id>/', TemplateBalance.as_view(), name='balance_template'),
    path('reports/payment-template/<int:id_payment>/', TemplatePayment.as_view(), name='payment_template'),
    path('reports/payment/<int:id_payment>/', PDFPayment.as_view(), name='payment_pdf'),
    path('reports/purchases/', PurchaseReportView.as_view(), name='purchase_report'),
    path('reports/sales/', SalesReportView.as_view(), name='sales_report'),
    path('reports/payments/', PymentReportView.as_view(), name='payment_report'),
    path('reports/collections/', CollectionsReportsView.as_view(), name='collections_report'),
    path('reports/balance/', BalanceReportView.as_view(), name='balance_report'),
    path('reports/sales-by-product/', SalesByProductReportView.as_view(), name='sales_by_product_report'),
    path('reports/partner-account-statement/', PartnerAccountStatmentView.as_view(), name='partner_account_statement'),
    path('reports/partner-account-statement/pdf/', PartnerAccountStatmentView.as_view(), {'template_name': 'reports/status_account.html'}, name='partner_account_statement_pdf'),
    path('reports/partner-search/', PartnerSearchView.as_view(), name='partner_search'),
    path('reports/collection-template/<int:id_collection>/', TemplateCollection.as_view(), name='collection_template'),
    path('reports/collection/<int:id_collection>/', PDFCollection.as_view(), name='collection_pdf'),
]
