from django.urls import path
from trade.views import (
    StockDayListView,
    StockDayCreateView,
    StockDayDeleteView,
    StockDayDetailView,
    DetailStockDetail,
    SingleStockDetailUpdateView,
    CustomerInvoiceList,
    CustomerOrdersList,
    SupplierOrdersList,
    SupplierInvoiceList,
    OrderDetailView,
    InvoiceDetailView,
    InvoiceFormView,
    AprovePurchaseOrderView,
    CreateInvoiceByOrder,
    CollectionsListView,
    PaymentsList,
    DeleteInvoiceView,
    SupplierInvoiceDetail,
    InvoiceSupplierUpdate,
    BatchOrderApprovalView,
    PaymentFormView,
    CollectionFormView,
    PaymentDetailView,
    PaymentPDFView,
)

# Importar APIs
from api.trade import (
    CollectionsCreateUpdateAPI,
    CollectionsVoidAPI,
    CollectionsContextAPI,
    PaymentCreateUpdateAPI,
    PaymentVoidAPI,
)

urlpatterns = [
    path('trade/<int:pk>/', DetailStockDetail.as_view(),name='stock_detail_detail'),
    path('trade/stock/', StockDayListView.as_view(), name='stock_list'),
    path('trade/stock/<int:pk>/', StockDayDetailView.as_view(), name='stock_detail'),
    path('trade/stock/nuevo/', StockDayCreateView.as_view(), name='stock_create'),
    path('trade/stock/eliminar/<int:pk>/', StockDayDeleteView.as_view(), name='stock_delete'),
    path('trade/stock/detalle/actualizar/<int:pk>/', SingleStockDetailUpdateView.as_view(), name='stock_detail_update'),
    path('trade/customer-invoices/', CustomerInvoiceList.as_view(), name='customer_invoice_list'),
    path('trade/customer-orders/', CustomerOrdersList.as_view(), name='customer_orders_list'),
    path('trade/supplier-orders/', SupplierOrdersList.as_view(), name='supplier_orders_list'),    
    path('trade/supplier-invoices/', SupplierInvoiceList.as_view(), name='supplier_invoice_list'),
    path('trade/supplier-invoice/update/<int:invoice_id>/', InvoiceSupplierUpdate.as_view(), name='invoice_supplier_update'),
    path('trade/invoice/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail_presentation'),
    path('trade/invoice-form/<int:pk>/', InvoiceFormView.as_view(), name='edit_invoice_form'),
    path('trade/invoice/update/<int:pk>/', InvoiceFormView.as_view(), name='update_invoice'),
    path('trade/invoice/delete/<int:pk>/', DeleteInvoiceView.as_view(), name='delete_invoice'),
    path('trade/supplier-invoice/<int:invoice_id>/', SupplierInvoiceDetail.as_view(), name='supplier_invoice_detail'),
    path('trade/order/<int:pk>/', OrderDetailView.as_view(), name='order_detail_presentation'),
    path('trade/order/aprove/<int:pk>/', AprovePurchaseOrderView.as_view(), name='aprove_purchase_order'),
    path('trade/aprove-batch-orders/', BatchOrderApprovalView.as_view(), name='aprove_batch_orders'),
    path('trade/order/generate-invoice/<int:pk>/', CreateInvoiceByOrder.as_view(), name='generate_invoice_by_order'),
    path('cobros/', CollectionsListView.as_view(), name='collections_list'),
    path('pagos/', PaymentsList.as_view(), name="payments_list"),
    path('pagos/nuevo/', PaymentFormView.as_view(), name='payment_create'),
    path('cobros/nuevo/', CollectionFormView.as_view(), name='collect_form'),
    path('api/collections/context-data/', CollectionsContextAPI.as_view(), name='collections_context_api'),
    path('api/collections/', CollectionsCreateUpdateAPI.as_view(), name='collections_create_api'),
    path('api/collections/<int:collection_id>/', CollectionsCreateUpdateAPI.as_view(), name='collections_update_api'),
    path('api/collections/<int:collection_id>/delete/', CollectionsVoidAPI.as_view(), name='collections_delete_api'),
    path('api/collections/delete/', CollectionsVoidAPI.as_view(), name='collections_bulk_delete_api'),
    path('api/payments/', PaymentCreateUpdateAPI.as_view(), name='payments_create_api'),
    path('api/payments/<int:payment_id>/delete/', PaymentVoidAPI.as_view(), name='payments_delete_api'),
    path('api/payments/delete/', PaymentVoidAPI.as_view(), name='payments_bulk_delete_api'),
    path('trade/payment/<int:pk>/', PaymentDetailView.as_view(), name='payment_detail'),
    path('trade/payment/<int:pk>/pdf/', PaymentPDFView.as_view(), name='payment_pdf'),
]
