"""
Django settings for ledger project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from common.secrets import MAIL_PASS, DEFAULT_DB

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dmiffk3lw9ht7&cvk#ix)y4b88xvy3c%0ci%@npnn&isex2*b$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'pytest_django',
    'user_sessions',
    'rest_framework',
    'django.contrib.humanize',
    'simple_history',
    'accounts',
    'partners',
    'products',
    'trade',
    'reports',
    'sellers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'user_sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'common.middleware.AccessLoggerMiddleware',  # Logging personalizado
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'user_sessions.backends.db'
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'kosmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'DIRS': ['templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kosmo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': DEFAULT_DB,
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-Es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2]+['static']),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.sep.join(os.path.abspath(
    __file__).split(os.sep)[:-2]+['media'])


STATIC_URL = '/static/'
STATIC_ROOT = os.sep.join(os.path.abspath(
    __file__).split(os.sep)[:-2]+['static_django'])

# STATIC_ROOT = os.path.join(os.path.abspath(
#     __file__).split(os.sep)[:-2]+['static_django'])


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuario Peronalizado
AUTH_USER_MODEL = 'accounts.CustomUserModel'
AUTHENTICATION_BACKENDS = [
    'common.EmailBackEndAuth.EmailBackEndAuth'
]

LOGIN = '/accounts/login/'

CSRF_TRUSTED_ORIGINS = [
    'https://146.190.56.181',
    'http://146.190.56.181',
    'http://app.kosmoflowers.com',
    'https://app.kosmoflowers.com',
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://test.kosmoflowers.com:5050',
    'https://test.kosmoflowers.com:5050'
]


PATH_LOGS = os.path.join(os.path.dirname(BASE_DIR), 'logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': PATH_LOGS + 'django_error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


# Reconocineto entorno
IS_IN_PRODUCTION = True
if 'eduardo' in os.path.abspath(__file__):
    IS_IN_PRODUCTION = False

# URL base para generación de reportes PDF
if IS_IN_PRODUCTION:
    BASE_URL = 'https://app.kosmoflowers.com'
else:
    BASE_URL = 'http://localhost:8000'

JET_DEFAULT_THEME = 'default'
JET_SIDE_MENU_COMPACT = True

# Datos bancarios para pagos y cobros
BANK_ACCOUNT = {
    'bank_name': 'Banco Pacifico',
    'account_number': '1067343082',
    'account_type': 'Corriente',
    'account_holder': 'Kosmo Flowers SAS',
    'bank_address': 'P. Icaza y Pedro Carbo',
    'bank_email': 'info@kosmoflowers.com'
}


# Correo electrónico para notificaciones
EMAIL_SETTINGS = {
    'host': 'smtp.kosmoflowers.com',
    'port': 587,
    'username': 'app-kosmoflowers@dev-7.com',
    'password': MAIL_PASS,
    'use_tls': True
}
